export default {
    LOGIN_SUCCESS: 'LOGIN_SUCCESS',
    LOGOUT_USER: 'LOGOUT_USER',
    CLOSE_LOGOUT_DIALOG: 'CLOSE_LOGOUT_DIALOG',
    OPEN_LOGOUT_DIALOG: 'OPEN_LOGOUT_DIALOG',
    DOWNLOAD_IMAGES: 'DOWNLOAD_IMAGES',
    IMAGE_DETAIL: 'IMAGE_DETAIL',
    IMAGE_UPLOAD_SUCCESS: 'IMAGE_UPLOAD_SUCCESS'
}
