export default {
    LOGIN_SUCCESS: 'LOGIN_SUCCESS',
    LOGOUT_USER: 'LOGOUT_USER',
    CLOSE_LOGOUT_DIALOG: 'CLOSE_LOGOUT_DIALOG',
    OPEN_LOGOUT_DIALOG: 'OPEN_LOGOUT_DIALOG',
    DOWNLOAD_IMAGES: 'DOWNLOAD_IMAGES',
    IMAGE_DETAIL: 'IMAGE_DETAIL',
    IMAGE_UPLOAD_SUCCESS: 'IMAGE_UPLOAD_SUCCESS',
    GET_ALL_TASKS_FOR_USER: 'GET_ALL_TASKS_FOR_USER',
    SET_TASK_FOR_DETAIL: 'SET_TASK_FOR_DETAIL',
    GET_ALL_USERS: 'GET_ALL_USERS',
    NEW_TASK: 'NEW_TASK',
    GET_TASKS_TO_MANAGE: 'GET_TASKS_TO_MANAGE'
}
